/**
 * Generates src/shared/build-info.generated.ts with the current timestamp
 * baked in as a constant. Run before every build so the app title shows
 * the actual build time, not the startup time.
 */

const getISOWeek = (d: Date): number => {
	const date = new Date(Date.UTC(d.getFullYear(), d.getMonth(), d.getDate()));
	date.setUTCDate(date.getUTCDate() + 4 - (date.getUTCDay() || 7));
	const yearStart = new Date(Date.UTC(date.getUTCFullYear(), 0, 1));
	return Math.ceil(((date.getTime() - yearStart.getTime()) / 86400000 + 1) / 7);
};

const formatDateTime = (d: Date) => {
	const date = d.toLocaleDateString("en-GB", {
		weekday: "short",
		day: "numeric",
		month: "short",
		year: "numeric",
	});
	const time = d.toLocaleTimeString("en-GB", {
		hour: "2-digit",
		minute: "2-digit",
		second: "2-digit",
	});
	return `${date} · W${String(getISOWeek(d)).padStart(2, "0")} · ${time}`;
};

const buildTime = formatDateTime(new Date());
const outPath = `${import.meta.dir}/../src/shared/build-info.generated.ts`;

const content = `// Auto-generated by scripts/generate-build-info.ts — do not edit
export const BUILD_TIME = ${JSON.stringify(buildTime)};
`;

await Bun.write(outPath, content);
console.log(`[build-info] ${buildTime} → src/shared/build-info.generated.ts`);
